// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'5743c851c43874f6e24bb17311ca7e32f4842d6510949bd9045bfcca02ed0484'>;
export type ExecutionHash =
  ExecutionHashBase<'96a4874a56e74708ef8b079d11c7002e9c9f76a0f7d35a1231973a094a878de1'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly travellerId: CodecTypes['pg/text@1']['output'] | null;
      readonly reminderId: CodecTypes['pg/text@1']['output'] | null;
      readonly eventType:
        | 'TRAVELLER_CREATED'
        | 'TRAVELLER_UPDATED'
        | 'FLIGHT_CREATED'
        | 'FLIGHT_UPDATED'
        | 'REMINDER_CREATED'
        | 'REMINDER_DUE'
        | 'ADMIN_ADVANCE_NOTIFICATION_SENT'
        | 'TRAVELLER_REMINDER_SENT'
        | 'ADMIN_CONFIRMATION_SENT'
        | 'REMINDER_FAILED'
        | 'REMINDER_RETRY_SCHEDULED'
        | 'REMINDER_CANCELLED';
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly metadata: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Flight: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly travellerId: CodecTypes['pg/text@1']['output'];
      readonly origin: CodecTypes['pg/text@1']['output'];
      readonly destination: CodecTypes['pg/text@1']['output'];
      readonly departureAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly arrivalAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly layoverCity: CodecTypes['pg/text@1']['output'] | null;
      readonly layoverBeginsAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly layoverEndsAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly layoverDuration: CodecTypes['pg/text@1']['output'] | null;
      readonly sheetRow: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Reminder: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly reminderId: CodecTypes['pg/text@1']['output'];
      readonly flightId: CodecTypes['pg/text@1']['output'];
      readonly scheduledFor: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SENT' | 'FAILED' | 'CANCELLED';
      readonly attemptCount: CodecTypes['pg/int4@1']['output'];
      readonly sentAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly failedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly errorMessage: CodecTypes['pg/text@1']['output'] | null;
      readonly providerMessageId: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Traveller: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly sheetRow: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly travellerId: CodecTypes['pg/text@1']['input'] | null;
      readonly reminderId: CodecTypes['pg/text@1']['input'] | null;
      readonly eventType:
        | 'TRAVELLER_CREATED'
        | 'TRAVELLER_UPDATED'
        | 'FLIGHT_CREATED'
        | 'FLIGHT_UPDATED'
        | 'REMINDER_CREATED'
        | 'REMINDER_DUE'
        | 'ADMIN_ADVANCE_NOTIFICATION_SENT'
        | 'TRAVELLER_REMINDER_SENT'
        | 'ADMIN_CONFIRMATION_SENT'
        | 'REMINDER_FAILED'
        | 'REMINDER_RETRY_SCHEDULED'
        | 'REMINDER_CANCELLED';
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly metadata: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Flight: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly travellerId: CodecTypes['pg/text@1']['input'];
      readonly origin: CodecTypes['pg/text@1']['input'];
      readonly destination: CodecTypes['pg/text@1']['input'];
      readonly departureAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly arrivalAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly layoverCity: CodecTypes['pg/text@1']['input'] | null;
      readonly layoverBeginsAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly layoverEndsAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly layoverDuration: CodecTypes['pg/text@1']['input'] | null;
      readonly sheetRow: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Reminder: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly reminderId: CodecTypes['pg/text@1']['input'];
      readonly flightId: CodecTypes['pg/text@1']['input'];
      readonly scheduledFor: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SENT' | 'FAILED' | 'CANCELLED';
      readonly attemptCount: CodecTypes['pg/int4@1']['input'];
      readonly sentAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly failedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly errorMessage: CodecTypes['pg/text@1']['input'] | null;
      readonly providerMessageId: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Traveller: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly sheetRow: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly auditLog: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly eventType:
        | 'TRAVELLER_CREATED'
        | 'TRAVELLER_UPDATED'
        | 'FLIGHT_CREATED'
        | 'FLIGHT_UPDATED'
        | 'REMINDER_CREATED'
        | 'REMINDER_DUE'
        | 'ADMIN_ADVANCE_NOTIFICATION_SENT'
        | 'TRAVELLER_REMINDER_SENT'
        | 'ADMIN_CONFIRMATION_SENT'
        | 'REMINDER_FAILED'
        | 'REMINDER_RETRY_SCHEDULED'
        | 'REMINDER_CANCELLED';
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly metadata: CodecTypes['pg/text@1']['output'] | null;
      readonly reminderId: CodecTypes['pg/text@1']['output'] | null;
      readonly travellerId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly flight: {
      readonly arrivalAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly departureAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly destination: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly layoverBeginsAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly layoverCity: CodecTypes['pg/text@1']['output'] | null;
      readonly layoverDuration: CodecTypes['pg/text@1']['output'] | null;
      readonly layoverEndsAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly origin: CodecTypes['pg/text@1']['output'];
      readonly sheetRow: CodecTypes['pg/int4@1']['output'];
      readonly travellerId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly reminder: {
      readonly attemptCount: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly errorMessage: CodecTypes['pg/text@1']['output'] | null;
      readonly failedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly flightId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly providerMessageId: CodecTypes['pg/text@1']['output'] | null;
      readonly reminderId: CodecTypes['pg/text@1']['output'];
      readonly scheduledFor: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly sentAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly status: 'PENDING' | 'PROCESSING' | 'SENT' | 'FAILED' | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly traveller: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly sheetRow: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly auditLog: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly eventType:
        | 'TRAVELLER_CREATED'
        | 'TRAVELLER_UPDATED'
        | 'FLIGHT_CREATED'
        | 'FLIGHT_UPDATED'
        | 'REMINDER_CREATED'
        | 'REMINDER_DUE'
        | 'ADMIN_ADVANCE_NOTIFICATION_SENT'
        | 'TRAVELLER_REMINDER_SENT'
        | 'ADMIN_CONFIRMATION_SENT'
        | 'REMINDER_FAILED'
        | 'REMINDER_RETRY_SCHEDULED'
        | 'REMINDER_CANCELLED';
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly metadata: CodecTypes['pg/text@1']['input'] | null;
      readonly reminderId: CodecTypes['pg/text@1']['input'] | null;
      readonly travellerId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly flight: {
      readonly arrivalAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly departureAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly destination: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly layoverBeginsAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly layoverCity: CodecTypes['pg/text@1']['input'] | null;
      readonly layoverDuration: CodecTypes['pg/text@1']['input'] | null;
      readonly layoverEndsAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly origin: CodecTypes['pg/text@1']['input'];
      readonly sheetRow: CodecTypes['pg/int4@1']['input'];
      readonly travellerId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly reminder: {
      readonly attemptCount: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly errorMessage: CodecTypes['pg/text@1']['input'] | null;
      readonly failedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly flightId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly providerMessageId: CodecTypes['pg/text@1']['input'] | null;
      readonly reminderId: CodecTypes['pg/text@1']['input'];
      readonly scheduledFor: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly sentAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly status: 'PENDING' | 'PROCESSING' | 'SENT' | 'FAILED' | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly traveller: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly sheetRow: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Traveller = {
    id: CodecTypes['pg/text@1']['output'];
    sheetRow: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    location: CodecTypes['pg/text@1']['output'] | null;
    email: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    auditLogs: public_AuditLog[];
    flights: public_Flight[];
    readonly [RelationKeys]?: 'auditLogs' | 'flights';
  };
  export type public_Flight = {
    id: CodecTypes['pg/text@1']['output'];
    travellerId: CodecTypes['pg/text@1']['output'];
    origin: CodecTypes['pg/text@1']['output'];
    destination: CodecTypes['pg/text@1']['output'];
    departureAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    arrivalAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    layoverCity: CodecTypes['pg/text@1']['output'] | null;
    layoverBeginsAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    layoverEndsAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    layoverDuration: CodecTypes['pg/text@1']['output'] | null;
    sheetRow: CodecTypes['pg/int4@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    reminder: public_Reminder | null;
    traveller: public_Traveller;
    readonly [RelationKeys]?: 'reminder' | 'traveller';
  };
  export type public_Reminder = {
    id: CodecTypes['pg/text@1']['output'];
    reminderId: CodecTypes['pg/text@1']['output'];
    flightId: CodecTypes['pg/text@1']['output'];
    scheduledFor: CodecTypes['pg/timestamptz-temporal@1']['output'];
    status: 'PENDING' | 'PROCESSING' | 'SENT' | 'FAILED' | 'CANCELLED';
    attemptCount: CodecTypes['pg/int4@1']['output'];
    sentAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    failedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    nextAttemptAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    errorMessage: CodecTypes['pg/text@1']['output'] | null;
    providerMessageId: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    auditLogs: public_AuditLog[];
    flight: public_Flight;
    readonly [RelationKeys]?: 'auditLogs' | 'flight';
  };
  export type public_AuditLog = {
    id: CodecTypes['pg/text@1']['output'];
    travellerId: CodecTypes['pg/text@1']['output'] | null;
    reminderId: CodecTypes['pg/text@1']['output'] | null;
    eventType:
      | 'TRAVELLER_CREATED'
      | 'TRAVELLER_UPDATED'
      | 'FLIGHT_CREATED'
      | 'FLIGHT_UPDATED'
      | 'REMINDER_CREATED'
      | 'REMINDER_DUE'
      | 'ADMIN_ADVANCE_NOTIFICATION_SENT'
      | 'TRAVELLER_REMINDER_SENT'
      | 'ADMIN_CONFIRMATION_SENT'
      | 'REMINDER_FAILED'
      | 'REMINDER_RETRY_SCHEDULED'
      | 'REMINDER_CANCELLED';
    message: CodecTypes['pg/text@1']['output'];
    metadata: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    reminder: public_Reminder | null;
    traveller: public_Traveller | null;
    readonly [RelationKeys]?: 'reminder' | 'traveller';
  };
}

export declare const models: {
  public: {
    Traveller: Models.public_Traveller;
    Flight: Models.public_Flight;
    Reminder: Models.public_Reminder;
    AuditLog: Models.public_AuditLog;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly auditLog: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly travellerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly reminderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly eventType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly message: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly metadata: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'auditLog_createdAt_idx_9575dbd7';
                  readonly prefix: 'auditLog_createdAt_idx';
                  readonly columns: readonly ['createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'auditLog_eventType_idx_e4cf7742';
                  readonly prefix: 'auditLog_eventType_idx';
                  readonly columns: readonly ['eventType'];
                  readonly unique: false;
                },
                {
                  readonly name: 'auditLog_travellerId_idx_6409e652';
                  readonly prefix: 'auditLog_travellerId_idx';
                  readonly columns: readonly ['travellerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'auditLog_reminderId_idx_273293f9';
                  readonly prefix: 'auditLog_reminderId_idx';
                  readonly columns: readonly ['reminderId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'auditLog';
                    readonly columns: readonly ['travellerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'traveller';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'auditLog';
                    readonly columns: readonly ['reminderId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reminder';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly flight: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly travellerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly origin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly destination: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly departureAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly arrivalAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly layoverCity: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly layoverBeginsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly layoverEndsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly layoverDuration: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly sheetRow: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['sheetRow'] }];
              indexes: readonly [
                {
                  readonly name: 'flight_travellerId_idx_6409e652';
                  readonly prefix: 'flight_travellerId_idx';
                  readonly columns: readonly ['travellerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'flight';
                    readonly columns: readonly ['travellerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'traveller';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly reminder: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reminderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flightId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly scheduledFor: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly attemptCount: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly sentAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly failedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly nextAttemptAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly errorMessage: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly providerMessageId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['reminderId'] },
                { readonly columns: readonly ['flightId'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reminder';
                    readonly columns: readonly ['flightId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'flight';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly traveller: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sheetRow: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly location: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['sheetRow'] },
                { readonly columns: readonly ['email'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly AuditEventType: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'TRAVELLER_CREATED',
                'TRAVELLER_UPDATED',
                'FLIGHT_CREATED',
                'FLIGHT_UPDATED',
                'REMINDER_CREATED',
                'REMINDER_DUE',
                'ADMIN_ADVANCE_NOTIFICATION_SENT',
                'TRAVELLER_REMINDER_SENT',
                'ADMIN_CONFIRMATION_SENT',
                'REMINDER_FAILED',
                'REMINDER_RETRY_SCHEDULED',
                'REMINDER_CANCELLED',
              ];
            };
            readonly ReminderStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly traveller: { readonly namespace: 'public' & NamespaceId; readonly model: 'Traveller' };
    readonly flight: { readonly namespace: 'public' & NamespaceId; readonly model: 'Flight' };
    readonly reminder: { readonly namespace: 'public' & NamespaceId; readonly model: 'Reminder' };
    readonly auditLog: { readonly namespace: 'public' & NamespaceId; readonly model: 'AuditLog' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AuditLog: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly travellerId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reminderId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly message: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metadata: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly reminder: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reminder';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['reminderId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly traveller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Traveller';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['travellerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'auditLog';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly travellerId: { readonly column: 'travellerId' };
                readonly reminderId: { readonly column: 'reminderId' };
                readonly eventType: { readonly column: 'eventType' };
                readonly message: { readonly column: 'message' };
                readonly metadata: { readonly column: 'metadata' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Flight: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly travellerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly origin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly destination: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly departureAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly arrivalAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly layoverCity: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly layoverBeginsAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly layoverEndsAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly layoverDuration: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sheetRow: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly reminder: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reminder';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['flightId'];
                };
              };
              readonly traveller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Traveller';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['travellerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'flight';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly travellerId: { readonly column: 'travellerId' };
                readonly origin: { readonly column: 'origin' };
                readonly destination: { readonly column: 'destination' };
                readonly departureAt: { readonly column: 'departureAt' };
                readonly arrivalAt: { readonly column: 'arrivalAt' };
                readonly layoverCity: { readonly column: 'layoverCity' };
                readonly layoverBeginsAt: { readonly column: 'layoverBeginsAt' };
                readonly layoverEndsAt: { readonly column: 'layoverEndsAt' };
                readonly layoverDuration: { readonly column: 'layoverDuration' };
                readonly sheetRow: { readonly column: 'sheetRow' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Reminder: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reminderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly flightId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly scheduledFor: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly attemptCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sentAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly failedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly nextAttemptAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly errorMessage: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly providerMessageId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly auditLogs: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AuditLog';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reminderId'];
                };
              };
              readonly flight: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Flight';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['flightId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'reminder';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly reminderId: { readonly column: 'reminderId' };
                readonly flightId: { readonly column: 'flightId' };
                readonly scheduledFor: { readonly column: 'scheduledFor' };
                readonly status: { readonly column: 'status' };
                readonly attemptCount: { readonly column: 'attemptCount' };
                readonly sentAt: { readonly column: 'sentAt' };
                readonly failedAt: { readonly column: 'failedAt' };
                readonly nextAttemptAt: { readonly column: 'nextAttemptAt' };
                readonly errorMessage: { readonly column: 'errorMessage' };
                readonly providerMessageId: { readonly column: 'providerMessageId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Traveller: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sheetRow: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly location: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly auditLogs: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AuditLog';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['travellerId'];
                };
              };
              readonly flights: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Flight';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['travellerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'traveller';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly sheetRow: { readonly column: 'sheetRow' };
                readonly name: { readonly column: 'name' };
                readonly location: { readonly column: 'location' };
                readonly email: { readonly column: 'email' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly ReminderStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PROCESSING'; readonly value: 'PROCESSING' },
              { readonly name: 'SENT'; readonly value: 'SENT' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly AuditEventType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'TRAVELLER_CREATED'; readonly value: 'TRAVELLER_CREATED' },
              { readonly name: 'TRAVELLER_UPDATED'; readonly value: 'TRAVELLER_UPDATED' },
              { readonly name: 'FLIGHT_CREATED'; readonly value: 'FLIGHT_CREATED' },
              { readonly name: 'FLIGHT_UPDATED'; readonly value: 'FLIGHT_UPDATED' },
              { readonly name: 'REMINDER_CREATED'; readonly value: 'REMINDER_CREATED' },
              { readonly name: 'REMINDER_DUE'; readonly value: 'REMINDER_DUE' },
              {
                readonly name: 'ADMIN_ADVANCE_NOTIFICATION_SENT';
                readonly value: 'ADMIN_ADVANCE_NOTIFICATION_SENT';
              },
              {
                readonly name: 'TRAVELLER_REMINDER_SENT';
                readonly value: 'TRAVELLER_REMINDER_SENT';
              },
              {
                readonly name: 'ADMIN_CONFIRMATION_SENT';
                readonly value: 'ADMIN_CONFIRMATION_SENT';
              },
              { readonly name: 'REMINDER_FAILED'; readonly value: 'REMINDER_FAILED' },
              {
                readonly name: 'REMINDER_RETRY_SCHEDULED';
                readonly value: 'REMINDER_RETRY_SCHEDULED';
              },
              { readonly name: 'REMINDER_CANCELLED'; readonly value: 'REMINDER_CANCELLED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'auditLog';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'flight';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'flight';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'reminder';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'reminder';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'traveller';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'traveller';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
